import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/componens/Essential/navbar";
import "./globals.css";
import FooterSection from "@/componens/Essential/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <div className="h-20">
        <NavBar/>
      </div>
      <div className="flex flex-col grow">
        {children}
      </div>
      <div className="h-40 sticky ">
        <FooterSection/>
      </div>
      </body>
    </html>
  );
}
